GET http://localhost:3005/users

###

POST http://localhost:3005/users/login
Content-Type: application/json

{
    "userName":"Cornelia",
    "password":"Lösenord"
}

###

GET http://localhost:3005/posts

###

POST http://localhost:3005/posts/new
Content-Type: application/json

{   
    "userId": 9, 
    "title":"HOLAHOLA",
    "message":"<p>Moppa, dammsuga, putsa fönster</p>"
}

###

POST http://localhost:3005/posts/all
Content-Type: application/json

{
    "userId":8
}

###

POST http://localhost:3005/posts/findpost
Content-Type: application/json

{
    "userId":10,
    "id":8
}

###

POST http://localhost:3005/posts/change/
Content-Type: application/json

{
    "title":"Hej",
    "id":32,
    "userId":8,
    "message":"<h2><span style='background-color: rgb(191, 237, 210);'>sdfasdfasdfasdf</span></h2><p>asdfasdfsadfas</p>"
}

###

POST http://localhost:3005/posts/remove
Content-Type: application/json

{
    "id":31
}